### ISSUE TITLE
index.js runError

### ISSUE THREAD

**Issue by 1404536198lj** [YYago/summarybuilder#1]
/usr/lib/node_modules/summarybuilder/index.js:12
let optCount = opts.length;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3

**Comment by YYago** [comment]
语法错误......这就悲剧了（我会在下一次更新时加上：`“use strict”`，应该能解决这个问题）。

事实上已经更新了[v1.4.4](https://www.npmjs.com/package/summarybuilder)，你重新装下看看。如果依旧有问题还请回馈下。
